Commit of all code
Bronzza/HomeWork13Patterns pull request #1
Opened 2019-04-12 19:56 UTC by Bronzza

2019-04-13 10:15 UTC, Taniann requested changes
please resolve comments and add using of singleton pattern

2019-04-13 10:15 UTC, Taniann commented on src/main/java/patterns/abstractfactoryproxy/ConcreteProxyCreatror.java
> +public class ConcreteProxyCreatror {
ConcreteProxyCreator

2019-04-13 10:15 UTC, Taniann commented on src/main/java/patterns/abstractfactoryproxy/ProxyCounter.java
> +    public void count() {
better make method count return int instead of printing result in method

2019-04-13 10:15 UTC, Taniann commented on src/main/java/patterns/abstractfactoryproxy/ToFiveCounter.java
> +    public void count() {
the same

2019-04-13 14:06 UTC, Bronzza commented on src/main/java/patterns/abstractfactoryproxy/ConcreteProxyCreatror.java
> +public class ConcreteProxyCreatror {
What should I do here?

2019-04-14 15:14 UTC, Taniann approved these changes
good

2019-06-26 08:31 UTC, merged